#!/bin/sh

[ -z $1 ] && echo "No application supplied" 1>&2 && exit 1

which xdotool >/dev/null 2>&1 || { echo "Missing application - xdotool" 1>&2; exit 2; }

CMD=$@
WIN=$(xdotool getactivewindow)

xdotool windowstate --add HIDDEN $WIN
$CMD
xdotool windowstate --remove HIDDEN $WIN
